### ISSUE TITLE
builder

### ISSUE THREAD

**Issue by mennis** [9fans/plan9port#78]
To ensure that we don't break older OSes going forward perhaps a builder would be helpful.  

On a test repo this yml content was successful in configuring and running builders using travis-ci. It is unclear to me if this is actually building the fuse dependent components.  I am not sure how one would test that.

```
language: bash
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask install Caskroom/cask/osxfuse; fi
script: ./INSTALL
matrix:
  include:
    - os: linux
      language: bash
    - os: osx
      osx_image: xcode8.3
      language: bash
    - os: osx
      osx_image: xcode8.2
      language: bash
    - os: osx
      osx_image: xcode8.1
      language: bash
    - os: osx
      osx_image: xcode7.3
      language: bash
    - os: osx
      osx_image: xcode6.4
      language: bash
```
